夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏
RedTownServer/redtownserver.github.io pull request #5
Opened 2021-07-16 15:49 UTC by nekomikan-laboratory

夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏夏祭り用のホームページとなります。逃走中の時のお知らせで宣伝します。

2021-07-17 02:40 UTC, tprj requested changes
- 荒れるのでPR名を変更してください。
- ファイルサイズの大きい画像を使用するのはやめてください。

2021-07-17 05:01 UTC, nekomikan-laboratory commented
imgur上だとしても駄目なのですか
読み込みに時間がかかるということでふか

2021-07-17 06:42 UTC, nekomikan-laboratory commented
終わりました🥱

2021-07-17 09:58 UTC, moru348 commented
Fuck You　ぶち殺すぞ・・・・・・・・・ ゴミめら・・・・・・！

2021-07-19 15:48 UTC, moru348 approved these changes
画像でかすぎてはみ出してスクロールバー出てる+サイズのバランスが悪いからimgタグでheightかwidth指定したほうが見やすそうだけど、他のページもそうなってるから気にしてなかったら大丈夫(文字めっちゃちっちゃいのは多分サイトの仕様)

![image](https://user-images.githubusercontent.com/75235911/126187955-d81fd484-7767-43ce-b34f-30e24d63f0d9.png)

2021-07-22 15:30 UTC, nekomikan-laboratory commented
よろしく！！

2021-07-23 10:15 UTC, merged