event list
RedTownServer/redtownserver.github.io pull request #8
Opened 2021-08-27 09:40 UTC by nekomikan-laboratory

2021-08-31 17:49 UTC, tprj reviewed
これここに書いてる内容表示されちゃうけどいいの?

2021-09-08 12:10 UTC, nekomikan-laboratory commented
?

2021-09-19 12:33 UTC, tprj approved these changes

2021-09-19 12:39 UTC, tprj requested changes

2021-09-19 12:39 UTC, tprj commented on article/posts/member.md
> +RTSのプラグイン系統の制作を支えている**優しい**プログラマー。このサイトも制作している。住所特定大好き！
脚色があるため要修正

2021-10-03 09:36 UTC, moru348 commented
誤植ナシと判断しました！

2021-10-03 09:46 UTC, nekomikan-laboratory commented on article/posts/member.md
> +RTSのプラグイン系統の制作を支えている**優しい**プログラマー。このサイトも制作している。住所特定大好き！
OKb

2021-10-03 11:25 UTC, tprj approved these changes

2021-10-03 11:26 UTC, merged